# Welcome to Jekyll!

title: MonkeyLittle
email: john.turner@monkeylittle.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on Software Engineering, Infrastructure and everything in between.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.monkeylittle.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: monkeylittle_
github_username:  monkeylittle

# Banner Settings
banner:
  enabled: true
  slides:
    - post_id: /blog/2017/02/06/kubernetes-fundamentals
    - post_id: /blog/2017/02/07/deploying-jenkins-with-kubernetes
    - post_id: /blog/2017/02/08/adding-persistent-volumes-to-jenkins-with-kubernetes-volumes

# Post Settings
excerpt_separator: <!-- more -->
permalink: /blog/:year/:month/:day/:title.html

# Pagination Settings
paginate_path: /blog/page/:num
paginate: 5

# Disqus Settings
disqus:
  shortname: monkeylittle

# Sharing Settings
sharing:
  service: shareaholic
  enabled: true

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
